openapi: 3.0.0
info:
  title: WebServiceUas
  version: 1.0.0
servers:
  - url: http://localhost:8080
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /regis:
    post:
      tags:
        - default
      summary: UasRegis
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: balqis
                password: Balqis123
                email: balqisrosa@gmail.com
                phone_number: '083154664118'
                address: Jl.Adikusumah Bandung
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - default
      summary: UserLogin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: balqis
                password: Balqis123
                email: balqisrosa@gmail.com
                phone_number: '083154664118'
                address: Jl.Adikusumah Bandung
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /products:
    get:
      tags:
        - default
      summary: Product
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: ProductPost
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: jeans
                price: 100000
                stock: 5
                description: jeans limited edition
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /products/{productId}:
    put:
      tags:
        - default
      summary: ProductUpdate
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: jeans kulot
                price: 150000
                stock: 5
                description: jeans limited edition
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: DeleteProduct
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders:
    get:
      tags:
        - default
      summary: Order
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: OrderPost
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 3
                total: 250000
                status: Sukses
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders/{orderId}:
    put:
      tags:
        - default
      summary: OrderUpdate
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 3
                total: 250000
                status: gagal
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: OrderDelete
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
